### ISSUE TITLE
2.37.0 does not compile on OTP 28: regex list in CaptureDate's @filename_patterns cannot be injected into from_filename/1

### ISSUE THREAD

**Issue by timujinne** [BeamLabEU/phoenix_kit#855]
`phoenix_kit` 2.37.0 (hex) fails to compile as a dependency, and `main` at `190a6be0` fails the same way on a clean checkout.

```
== Compilation error in file lib/modules/storage/services/capture_date.ex ==
** (ArgumentError) cannot inject attribute @filename_patterns into function/macro because cannot escape #Reference<0.3284438819.1517944836.103459>. The supported values are: lists, tuples, maps, atoms, numbers, bitstrings, PIDs and remote functions in the format &Mod.fun/arity
    (elixir 1.18.4) lib/kernel.ex:3777: Kernel.do_at_escape/2
    (elixir 1.18.4) expanding macro: Kernel.@/1
    lib/modules/storage/services/capture_date.ex:302: PhoenixKit.Modules.Storage.CaptureDate.from_filename/1
```

Elixir 1.18.4, Erlang/OTP 28.3.2. `@filename_patterns` (capture_date.ex:88) is a list of `~r` sigils and `from_filename/1` (:302) reads it; a compiled regex carries a runtime reference on OTP 28, so the compiler refuses to escape the attribute into the function body. Introduced by c1285390 (V200 capture dates), so it affects every host on OTP 28 that bumps to 2.37.0 — we had to stay on 2.34.0.

Fix PR follows: build the list in a private function instead of an attribute (same sigils, same comments), which compiles everywhere.

**Comment by timujinne** [comment]
Verified on a real host (decor_3d_print, Elixir 1.18.4 / OTP 28.3.2): with 2.37.4 the app compiles clean and `mix phoenix_kit.update` migrated V199 → V200 without incident. Thanks for merging #856.
